
image: docker:stable

variables:
  DOCKER_DRIVER: overlay

before_script:
  - docker info
  - apk add --no-cache bash git
  - echo -e $SECRET_DOCKER_LOGIN_PASSWORD | docker login --username $SECRET_DOCKER_LOGIN_USERNAME --password-stdin

stages:
  - setup
  - minimal
  - full
  - extras
  - discord

do_setup:
  stage: setup
  before_script:
    - docker info
    - apk add --no-cache python3 python3-dev bash git alpine-sdk
    - echo -e $SECRET_DOCKER_LOGIN_PASSWORD | docker login --username $SECRET_DOCKER_LOGIN_USERNAME --password-stdin
    - docker system prune -af --volumes > /dev/null
  script:
    - rm -rf dockerfiles  # clear away autogen
    - python3 -m pip install -U pip
    - python3 -m pip install -U -r requirements.txt
    - python3 generate.py
    - cd dockerfiles
    - find ./ -name "*.sh" -exec chmod +x {} \;
    - cd ..
  artifacts:
    paths:
      - dockerfiles
    expire_in: 4 weeks

deploy_minimal:
  stage: minimal
  script:
    - cd dockerfiles
    - bash -c "GIT_HEAD="`git rev-list --count HEAD || echo unknown`+`git rev-parse --short HEAD || echo unknown`" ./deploy_target.sh 0_minimal"
    - cd ..
  artifacts:
    paths:
      - dockerfiles
    expire_in: 4 weeks
  dependencies:
    - do_setup

deploy_full:
  stage: full
  script:
    - cd dockerfiles
    - bash -c "GIT_HEAD="`git rev-list --count HEAD || echo unknown`+`git rev-parse --short HEAD || echo unknown`" ./deploy_target.sh 1_full"
    - cd ..
  artifacts:
    paths:
      - dockerfiles
    expire_in: 4 weeks
  dependencies:
    - do_setup
    - deploy_minimal

deploy_extras:
  stage: extras
  script:
    - cd dockerfiles
    - bash -c "GIT_HEAD="`git rev-list --count HEAD || echo unknown`+`git rev-parse --short HEAD || echo unknown`" ./deploy_target.sh 2_extra"
    - cd ..
  artifacts:
    paths:
      - dockerfiles
    expire_in: 4 weeks
  dependencies:
    - do_setup
    - deploy_minimal
    - deploy_full

deploy_final:
  stage: discord
  script:
    - cd dockerfiles
    - bash -c "GIT_HEAD="`git rev-list --count HEAD || echo unknown`+`git rev-parse --short HEAD || echo unknown`" ./deploy_target.sh discordpy"
    - cd ..
  after_script:
    - docker system prune -af --volumes > /dev/null
  artifacts:
    paths:
      - dockerfiles
    expire_in: 4 weeks
  dependencies:
    - do_setup
    - deploy_minimal
    - deploy_full
    - deploy_extras
