
image: docker:stable

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - docker info
  - apk add --no-cache python3 bash git
  - echo -e $SECRET_DOCKER_LOGIN_PASSWORD | docker login --username $SECRET_DOCKER_LOGIN_USERNAME --password-stdin

after_script:
  - docker system prune -af --volumes > /dev/null

build:
  stage: build
  script:
    - rm -rf dockerfiles # clear away autogen'd files if they're there
    - python3 -m pip install -U pip
    - python3 -m pip install -U -r requirements.txt
    - python3 generate.py
    - cd dockerfiles
    - find ./ -name "*.sh" -exec chmod +x {} \;
    - bash -c "GIT_HEAD=(`git rev-list --count HEAD || echo unknown`+`git rev-parse --short HEAD || echo unknown`) ./deploy_all.sh"
