
# this file works as a combination of Dockerfile arguments and Docker tags
# x: ["y", "z"] means the variable is x, and it is reflected in Docker tags y and z.
# tags should decrease in specificity along the list
# a blank tag means it is implicit when omitted
# this is used to automatically generate the Dockerfiles, metadata and readme.

python_versions:
  3.7.1: ["3.7.1", "3.7"]
  3.6.7: ["3.6.7", "3.6", ""]
  #3.5.5: ["3.5.5", "3.5"] # dropped because no stretch image and libc has some issues
  #3.4.8: ["3.4.8", "3.4"] # dropped because not compatible with a lot of async drivers

distros:
  stretch: ["stretch", ""]
  slim-stretch: ["slim"]
  alpine: ["alpine"]

checkouts:
  rewrite: ["1.0", "rewrite"]
  async: ["0.16", "async", ""]

# these don't follow the above syntax as they're just pulled by the templates
minor_deps:
  asyncpg: asyncpg
  coverage: coverage
  flake8: flake8
  lxml: lxml
  matplotlib: matplotlib
  numpy: numpy
  Pillow: Pillow
  psutil: psutil
  pycryptodome: pycryptodome
  pylint: pylint
  pytest-cov: pytest-cov
  pytest-faulthandler: pytest-faulthandler
  ruamel.yaml: ruamel.yaml
  uvloop: uvloop
  youtube-dl: youtube-dl

major_deps:
  aiomysql: aiomysql
  aioredis: aioredis
  beautifulsoup4: beautifulsoup4
  cairosvg: cairosvg
  click: click
  colorlog: colorlog
  colorthief: colorthief
  fuzzywuzzy: fuzzywuzzy[speedup]
  humanize: humanize
  lru-dict: lru-dict
  objgraph: objgraph
  parsedatetime: parsedatetime
  python-dateutil: python-dateutil
  PyYAML: PyYAML
  sqlalchemy: sqlalchemy
  tabulate: tabulate
  tox: tox
  twine: twine
  uvloop: uvloop
  wand: wand

stage_types:
  0: ['minimal']
  1: ['full', '']
  2: ['extras']
