
# this file works as a combination of Dockerfile arguments and Docker tags
# x: ["y", "z"] means the variable is x, and it is reflected in Docker tags y and z.
# tags should decrease in specificity along the list
# a blank tag means it is implicit when omitted
# this is used to automatically generate the Dockerfiles, metadata and readme.

python_versions:
  3.6.5: ["3.6.5", "3.6", "3", ""]
  #3.5.5: ["3.5.5", "3.5"] # dropped because no stretch image and libc has some issues
  #3.4.8: ["3.4.8", "3.4"] # dropped because not compatible with a lot of async drivers

distros:
  stretch: ["stretch", ""]
  slim-stretch: ["slim-stretch", "slim"]
  alpine: ["alpine"]

checkouts:
  rewrite: ["1.0.0a", "1.0.0", "1.0", "rewrite"]
  async: ["0.16.12", "0.16", "async", ""]

minor_deps:
  - asyncpg
  - lxml
  - matplotlib
  - numpy
  - Pillow
  - psutil
  - pycrypto
  - pycryptodome
  - ruamel.yaml
  - uvloop

major_deps:
  - aiofiles
  - aiomysql
  - aioredis
  - beautifulsoup4
  - cairosvg
  - click
  - colorlog
  - colorthief
  - fuzzywuzzy[speedup]
  - humanize
  - lru-dict
  - objgraph
  - parsedatetime
  - pytest-cov
  - python-dateutil
  - PyYAML
  - sqlalchemy
  - tabulate
  - tox
  - twine
  - uvloop
  - wand
  - watchdog
  - youtube-dl
