
# this file works as a combination of Dockerfile arguments and Docker tags
# x: ["y", "z"] means the variable is x, and it is reflected in Docker tags y and z.
# tags should decrease in specificity along the list
# a blank tag means it is implicit when omitted
# this is used to automatically generate the Dockerfiles, metadata and readme.

# When updating this ALSO UPDATE .github/workflows/docker-build.yml !!
python_versions:
  "3.9.1":    ["3.9.1", "3.9", ""]
  "3.8.7":    ["3.8.7", "3.8"]
  "3.7.9":    ["3.7.9", "3.7"]
  "3.6.12":   ["3.6.12", "3.6"]

distros:
  buster: ["buster", ""]
  slim-buster: ["slim-buster", "slim"]
  alpine: ["alpine"]

checkouts:
  master: ["master", "dev"]
  "": ["pypi", "1.5", "1", ""]

# these don't follow the above syntax as they're just pulled by the templates
minor_deps:
  asyncpg: asyncpg
  click: click
  coverage: coverage
  flake8: flake8
  lxml: lxml
  matplotlib: matplotlib
  Pillow: Pillow
  psutil: psutil
  pycryptodome: pycryptodome
  pylint: pylint
  pytest-cov: pytest-cov
  PyYAML: PyYAML
  ruamel.yaml: "ruamel.yaml"
  toml: toml
  twine: twine

major_deps:
  aiomysql: aiomysql
  aioredis: aioredis
  beautifulsoup4: beautifulsoup4
  cairosvg: cairosvg
  colorlog: colorlog
  colorthief: colorthief
  fuzzywuzzy: fuzzywuzzy[speedup]
  h5py: h5py
  humanize: humanize
  lru-dict: lru-dict
  objgraph: objgraph
  parsedatetime: parsedatetime
  python-dateutil: python-dateutil
  sqlalchemy: sqlalchemy
  tabulate: tabulate
  tox: tox
  wand: wand

stage_types:
  0: ['minimal']
  1: ['full', '']
  2: ['extras']
