#!/bin/bash
set -euo pipefail

docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-stretch-1.0.0a
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-stretch-1.0.0
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-stretch-1.0
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-stretch-rewrite
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-1.0.0a
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-1.0.0
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-1.0
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-rewrite
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-stretch-1.0.0a
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-stretch-1.0.0
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-stretch-1.0
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-stretch-rewrite
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-1.0.0a
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-1.0.0
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-1.0
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-rewrite
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-stretch-1.0.0a
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-stretch-1.0.0
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-stretch-1.0
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-stretch-rewrite
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-1.0.0a
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-1.0.0
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-1.0
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-rewrite
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-stretch-1.0.0a
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-stretch-1.0.0
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-stretch-1.0
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-stretch-rewrite
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-1.0.0a
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-1.0.0
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-1.0
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-rewrite
