#!/bin/bash
set -euo pipefail

if docker build --no-cache -f stretch.Dockerfile --build-arg PYTHON_VERSION=3.7.0 --tag discord.py:build1-3.7.0-stretch --tag ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:build1-3.7.0-stretch .; then echo -e "BUILD build1-3.7.0-stretch" >> ${DOCKER_DISCORD_PY_PASSTMP:-/dev/null}; else echo -e "FAIL BUILD build1-3.7.0-stretch" | tee -a ${DOCKER_DISCORD_PY_FAILTMP:-/dev/null}; fi
if docker build --no-cache -f slim-stretch.Dockerfile --build-arg PYTHON_VERSION=3.7.0 --tag discord.py:build1-3.7.0-slim-stretch --tag ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:build1-3.7.0-slim-stretch .; then echo -e "BUILD build1-3.7.0-slim-stretch" >> ${DOCKER_DISCORD_PY_PASSTMP:-/dev/null}; else echo -e "FAIL BUILD build1-3.7.0-slim-stretch" | tee -a ${DOCKER_DISCORD_PY_FAILTMP:-/dev/null}; fi
if docker build --no-cache -f alpine.Dockerfile --build-arg PYTHON_VERSION=3.7.0 --tag discord.py:build1-3.7.0-alpine --tag ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:build1-3.7.0-alpine .; then echo -e "BUILD build1-3.7.0-alpine" >> ${DOCKER_DISCORD_PY_PASSTMP:-/dev/null}; else echo -e "FAIL BUILD build1-3.7.0-alpine" | tee -a ${DOCKER_DISCORD_PY_FAILTMP:-/dev/null}; fi
if docker build --no-cache -f stretch.Dockerfile --build-arg PYTHON_VERSION=3.6.6 --tag discord.py:build1-3.6.6-stretch --tag ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:build1-3.6.6-stretch .; then echo -e "BUILD build1-3.6.6-stretch" >> ${DOCKER_DISCORD_PY_PASSTMP:-/dev/null}; else echo -e "FAIL BUILD build1-3.6.6-stretch" | tee -a ${DOCKER_DISCORD_PY_FAILTMP:-/dev/null}; fi
if docker build --no-cache -f slim-stretch.Dockerfile --build-arg PYTHON_VERSION=3.6.6 --tag discord.py:build1-3.6.6-slim-stretch --tag ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:build1-3.6.6-slim-stretch .; then echo -e "BUILD build1-3.6.6-slim-stretch" >> ${DOCKER_DISCORD_PY_PASSTMP:-/dev/null}; else echo -e "FAIL BUILD build1-3.6.6-slim-stretch" | tee -a ${DOCKER_DISCORD_PY_FAILTMP:-/dev/null}; fi
if docker build --no-cache -f alpine.Dockerfile --build-arg PYTHON_VERSION=3.6.6 --tag discord.py:build1-3.6.6-alpine --tag ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:build1-3.6.6-alpine .; then echo -e "BUILD build1-3.6.6-alpine" >> ${DOCKER_DISCORD_PY_PASSTMP:-/dev/null}; else echo -e "FAIL BUILD build1-3.6.6-alpine" | tee -a ${DOCKER_DISCORD_PY_FAILTMP:-/dev/null}; fi
