#!/bin/bash
set -euo pipefail

docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-stretch-1.0.0a-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-stretch-1.0.0-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-stretch-1.0-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-stretch-rewrite-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-1.0.0a-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-1.0.0-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-1.0-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-rewrite-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-stretch-1.0.0a-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-stretch-1.0.0-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-stretch-1.0-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-stretch-rewrite-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-1.0.0a-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-1.0.0-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-1.0-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-rewrite-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-stretch-1.0.0a-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-stretch-1.0.0-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-stretch-1.0-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-stretch-rewrite-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-1.0.0a-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-1.0.0-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-1.0-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-rewrite-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:stretch-1.0.0a-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:stretch-1.0.0-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:stretch-1.0-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:stretch-rewrite-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:1.0.0a-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:1.0.0-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:1.0-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:rewrite-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-stretch-1.0.0a-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-stretch-1.0.0a
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-stretch-1.0.0-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-stretch-1.0.0
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-stretch-1.0-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-stretch-1.0
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-stretch-rewrite-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-stretch-rewrite
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-1.0.0a-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-1.0.0a
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-1.0.0-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-1.0.0
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-1.0-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-1.0
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-rewrite-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-rewrite
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-stretch-1.0.0a-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-stretch-1.0.0a
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-stretch-1.0.0-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-stretch-1.0.0
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-stretch-1.0-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-stretch-1.0
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-stretch-rewrite-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-stretch-rewrite
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-1.0.0a-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-1.0.0a
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-1.0.0-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-1.0.0
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-1.0-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-1.0
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-rewrite-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-rewrite
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-stretch-1.0.0a-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-stretch-1.0.0a
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-stretch-1.0.0-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-stretch-1.0.0
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-stretch-1.0-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-stretch-1.0
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-stretch-rewrite-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-stretch-rewrite
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-1.0.0a-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-1.0.0a
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-1.0.0-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-1.0.0
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-1.0-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-1.0
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-rewrite-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-rewrite
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:stretch-1.0.0a-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:stretch-1.0.0a
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:stretch-1.0.0-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:stretch-1.0.0
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:stretch-1.0-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:stretch-1.0
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:stretch-rewrite-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:stretch-rewrite
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:1.0.0a-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:1.0.0a
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:1.0.0-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:1.0.0
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:1.0-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:1.0
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:rewrite-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:rewrite
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-stretch-1.0.0a-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-stretch-1.0.0-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-stretch-1.0-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-stretch-rewrite-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-1.0.0a-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-1.0.0-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-1.0-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-rewrite-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-stretch-1.0.0a-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-stretch-1.0.0-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-stretch-1.0-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-stretch-rewrite-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-1.0.0a-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-1.0.0-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-1.0-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-rewrite-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-stretch-1.0.0a-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-stretch-1.0.0-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-stretch-1.0-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-stretch-rewrite-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-1.0.0a-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-1.0.0-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-1.0-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-rewrite-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:stretch-1.0.0a-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:stretch-1.0.0-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:stretch-1.0-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:stretch-rewrite-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:1.0.0a-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:1.0.0-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:1.0-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:rewrite-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-stretch-0.16.12-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-stretch-0.16-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-stretch-async-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-stretch-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-0.16.12-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-0.16-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-async-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-stretch-0.16.12-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-stretch-0.16-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-stretch-async-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-stretch-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-0.16.12-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-0.16-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-async-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-stretch-0.16.12-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-stretch-0.16-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-stretch-async-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-stretch-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-0.16.12-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-0.16-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-async-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:stretch-0.16.12-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:stretch-0.16-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:stretch-async-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:stretch-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:0.16.12-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:0.16-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:async-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-stretch-0.16.12-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-stretch-0.16.12
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-stretch-0.16-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-stretch-0.16
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-stretch-async-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-stretch-async
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-stretch-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-stretch
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-0.16.12-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-0.16.12
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-0.16-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-0.16
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-async-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-async
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-stretch-0.16.12-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-stretch-0.16.12
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-stretch-0.16-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-stretch-0.16
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-stretch-async-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-stretch-async
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-stretch-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-stretch
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-0.16.12-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-0.16.12
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-0.16-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-0.16
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-async-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-async
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-stretch-0.16.12-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-stretch-0.16.12
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-stretch-0.16-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-stretch-0.16
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-stretch-async-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-stretch-async
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-stretch-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-stretch
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-0.16.12-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-0.16.12
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-0.16-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-0.16
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-async-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-async
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:stretch-0.16.12-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:stretch-0.16.12
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:stretch-0.16-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:stretch-0.16
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:stretch-async-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:stretch-async
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:stretch-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:stretch
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:0.16.12-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:0.16.12
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:0.16-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:0.16
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:async-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:async
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:latest
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-stretch-0.16.12-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-stretch-0.16-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-stretch-async-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-stretch-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-0.16.12-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-0.16-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-async-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-stretch-0.16.12-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-stretch-0.16-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-stretch-async-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-stretch-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-0.16.12-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-0.16-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-async-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-stretch-0.16.12-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-stretch-0.16-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-stretch-async-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-stretch-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-0.16.12-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-0.16-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-async-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:stretch-0.16.12-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:stretch-0.16-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:stretch-async-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:stretch-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:0.16.12-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:0.16-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:async-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-stretch-1.0.0a-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-stretch-1.0.0-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-stretch-1.0-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-stretch-rewrite-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-1.0.0a-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-1.0.0-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-1.0-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-rewrite-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-stretch-1.0.0a-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-stretch-1.0.0-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-stretch-1.0-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-stretch-rewrite-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-1.0.0a-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-1.0.0-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-1.0-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-rewrite-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-stretch-1.0.0a-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-stretch-1.0.0-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-stretch-1.0-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-stretch-rewrite-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-1.0.0a-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-1.0.0-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-1.0-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-rewrite-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-stretch-1.0.0a-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-stretch-1.0.0-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-stretch-1.0-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-stretch-rewrite-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-1.0.0a-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-1.0.0-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-1.0-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-rewrite-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-stretch-1.0.0a-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-stretch-1.0.0a
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-stretch-1.0.0-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-stretch-1.0.0
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-stretch-1.0-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-stretch-1.0
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-stretch-rewrite-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-stretch-rewrite
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-1.0.0a-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-1.0.0a
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-1.0.0-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-1.0.0
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-1.0-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-1.0
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-rewrite-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-rewrite
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-stretch-1.0.0a-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-stretch-1.0.0a
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-stretch-1.0.0-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-stretch-1.0.0
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-stretch-1.0-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-stretch-1.0
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-stretch-rewrite-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-stretch-rewrite
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-1.0.0a-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-1.0.0a
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-1.0.0-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-1.0.0
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-1.0-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-1.0
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-rewrite-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-rewrite
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-stretch-1.0.0a-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-stretch-1.0.0a
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-stretch-1.0.0-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-stretch-1.0.0
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-stretch-1.0-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-stretch-1.0
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-stretch-rewrite-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-stretch-rewrite
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-1.0.0a-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-1.0.0a
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-1.0.0-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-1.0.0
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-1.0-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-1.0
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-rewrite-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-rewrite
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-stretch-1.0.0a-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-stretch-1.0.0a
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-stretch-1.0.0-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-stretch-1.0.0
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-stretch-1.0-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-stretch-1.0
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-stretch-rewrite-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-stretch-rewrite
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-1.0.0a-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-1.0.0a
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-1.0.0-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-1.0.0
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-1.0-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-1.0
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-rewrite-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-rewrite
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-stretch-1.0.0a-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-stretch-1.0.0-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-stretch-1.0-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-stretch-rewrite-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-1.0.0a-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-1.0.0-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-1.0-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-rewrite-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-stretch-1.0.0a-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-stretch-1.0.0-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-stretch-1.0-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-stretch-rewrite-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-1.0.0a-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-1.0.0-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-1.0-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-rewrite-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-stretch-1.0.0a-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-stretch-1.0.0-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-stretch-1.0-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-stretch-rewrite-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-1.0.0a-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-1.0.0-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-1.0-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-rewrite-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-stretch-1.0.0a-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-stretch-1.0.0-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-stretch-1.0-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-stretch-rewrite-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-1.0.0a-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-1.0.0-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-1.0-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-rewrite-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-stretch-0.16.12-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-stretch-0.16-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-stretch-async-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-stretch-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-0.16.12-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-0.16-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-async-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-stretch-0.16.12-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-stretch-0.16-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-stretch-async-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-stretch-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-0.16.12-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-0.16-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-async-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-stretch-0.16.12-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-stretch-0.16-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-stretch-async-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-stretch-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-0.16.12-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-0.16-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-async-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-stretch-0.16.12-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-stretch-0.16-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-stretch-async-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-stretch-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-0.16.12-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-0.16-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-async-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-stretch-0.16.12-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-stretch-0.16.12
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-stretch-0.16-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-stretch-0.16
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-stretch-async-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-stretch-async
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-stretch-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-stretch
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-0.16.12-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-0.16.12
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-0.16-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-0.16
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-async-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-async
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-stretch-0.16.12-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-stretch-0.16.12
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-stretch-0.16-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-stretch-0.16
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-stretch-async-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-stretch-async
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-stretch-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-stretch
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-0.16.12-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-0.16.12
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-0.16-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-0.16
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-async-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-async
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-stretch-0.16.12-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-stretch-0.16.12
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-stretch-0.16-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-stretch-0.16
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-stretch-async-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-stretch-async
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-stretch-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-stretch
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-0.16.12-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-0.16.12
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-0.16-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-0.16
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-async-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-async
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-stretch-0.16.12-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-stretch-0.16.12
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-stretch-0.16-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-stretch-0.16
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-stretch-async-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-stretch-async
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-stretch-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-stretch
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-0.16.12-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-0.16.12
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-0.16-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-0.16
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-async-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-async
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-stretch-0.16.12-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-stretch-0.16-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-stretch-async-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-stretch-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-0.16.12-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-0.16-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-async-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-slim-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-stretch-0.16.12-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-stretch-0.16-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-stretch-async-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-stretch-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-0.16.12-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-0.16-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-async-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-slim-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-stretch-0.16.12-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-stretch-0.16-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-stretch-async-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-stretch-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-0.16.12-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-0.16-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-async-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-slim-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-stretch-0.16.12-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-stretch-0.16-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-stretch-async-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-stretch-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-0.16.12-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-0.16-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-async-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:slim-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-alpine-1.0.0a-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-alpine-1.0.0-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-alpine-1.0-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-alpine-rewrite-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-alpine-1.0.0a-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-alpine-1.0.0-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-alpine-1.0-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-alpine-rewrite-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-alpine-1.0.0a-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-alpine-1.0.0-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-alpine-1.0-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-alpine-rewrite-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:alpine-1.0.0a-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:alpine-1.0.0-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:alpine-1.0-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:alpine-rewrite-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-alpine-1.0.0a-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-alpine-1.0.0a
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-alpine-1.0.0-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-alpine-1.0.0
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-alpine-1.0-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-alpine-1.0
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-alpine-rewrite-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-alpine-rewrite
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-alpine-1.0.0a-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-alpine-1.0.0a
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-alpine-1.0.0-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-alpine-1.0.0
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-alpine-1.0-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-alpine-1.0
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-alpine-rewrite-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-alpine-rewrite
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-alpine-1.0.0a-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-alpine-1.0.0a
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-alpine-1.0.0-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-alpine-1.0.0
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-alpine-1.0-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-alpine-1.0
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-alpine-rewrite-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-alpine-rewrite
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:alpine-1.0.0a-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:alpine-1.0.0a
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:alpine-1.0.0-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:alpine-1.0.0
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:alpine-1.0-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:alpine-1.0
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:alpine-rewrite-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:alpine-rewrite
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-alpine-1.0.0a-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-alpine-1.0.0-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-alpine-1.0-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-alpine-rewrite-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-alpine-1.0.0a-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-alpine-1.0.0-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-alpine-1.0-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-alpine-rewrite-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-alpine-1.0.0a-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-alpine-1.0.0-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-alpine-1.0-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-alpine-rewrite-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:alpine-1.0.0a-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:alpine-1.0.0-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:alpine-1.0-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:alpine-rewrite-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-alpine-0.16.12-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-alpine-0.16-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-alpine-async-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-alpine-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-alpine-0.16.12-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-alpine-0.16-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-alpine-async-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-alpine-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-alpine-0.16.12-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-alpine-0.16-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-alpine-async-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-alpine-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:alpine-0.16.12-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:alpine-0.16-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:alpine-async-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:alpine-minimal
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-alpine-0.16.12-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-alpine-0.16.12
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-alpine-0.16-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-alpine-0.16
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-alpine-async-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-alpine-async
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-alpine-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-alpine
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-alpine-0.16.12-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-alpine-0.16.12
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-alpine-0.16-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-alpine-0.16
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-alpine-async-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-alpine-async
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-alpine-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-alpine
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-alpine-0.16.12-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-alpine-0.16.12
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-alpine-0.16-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-alpine-0.16
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-alpine-async-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-alpine-async
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-alpine-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-alpine
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:alpine-0.16.12-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:alpine-0.16.12
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:alpine-0.16-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:alpine-0.16
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:alpine-async-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:alpine-async
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:alpine-full
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:alpine
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-alpine-0.16.12-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-alpine-0.16-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-alpine-async-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6.4-alpine-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-alpine-0.16.12-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-alpine-0.16-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-alpine-async-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3.6-alpine-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-alpine-0.16.12-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-alpine-0.16-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-alpine-async-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:3-alpine-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:alpine-0.16.12-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:alpine-0.16-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:alpine-async-extras
docker push ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:alpine-extras
