#!/bin/bash
set -euo pipefail

if docker build --no-cache --build-arg DOCKER_REPO=${DOCKER_UPLOAD_REPOSITORY:-gorialis} --build-arg PYTHON_VERSION=3.8.0b2 --build-arg DISTRO=buster --tag discord.py:build2-3.8.0b2-buster --tag ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:build2-3.8.0b2-buster .; then echo -e "BUILD build2-3.8.0b2-buster" >> ${DOCKER_DISCORD_PY_PASSTMP:-/dev/null}; else echo -e "FAIL BUILD build2-3.8.0b2-buster" | tee -a ${DOCKER_DISCORD_PY_FAILTMP:-/dev/null}; fi
if docker build --no-cache --build-arg DOCKER_REPO=${DOCKER_UPLOAD_REPOSITORY:-gorialis} --build-arg PYTHON_VERSION=3.8.0b2 --build-arg DISTRO=slim-buster --tag discord.py:build2-3.8.0b2-slim-buster --tag ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:build2-3.8.0b2-slim-buster .; then echo -e "BUILD build2-3.8.0b2-slim-buster" >> ${DOCKER_DISCORD_PY_PASSTMP:-/dev/null}; else echo -e "FAIL BUILD build2-3.8.0b2-slim-buster" | tee -a ${DOCKER_DISCORD_PY_FAILTMP:-/dev/null}; fi
if docker build --no-cache --build-arg DOCKER_REPO=${DOCKER_UPLOAD_REPOSITORY:-gorialis} --build-arg PYTHON_VERSION=3.8.0b2 --build-arg DISTRO=alpine --tag discord.py:build2-3.8.0b2-alpine --tag ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:build2-3.8.0b2-alpine .; then echo -e "BUILD build2-3.8.0b2-alpine" >> ${DOCKER_DISCORD_PY_PASSTMP:-/dev/null}; else echo -e "FAIL BUILD build2-3.8.0b2-alpine" | tee -a ${DOCKER_DISCORD_PY_FAILTMP:-/dev/null}; fi
if docker build --no-cache --build-arg DOCKER_REPO=${DOCKER_UPLOAD_REPOSITORY:-gorialis} --build-arg PYTHON_VERSION=3.7.4 --build-arg DISTRO=buster --tag discord.py:build2-3.7.4-buster --tag ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:build2-3.7.4-buster .; then echo -e "BUILD build2-3.7.4-buster" >> ${DOCKER_DISCORD_PY_PASSTMP:-/dev/null}; else echo -e "FAIL BUILD build2-3.7.4-buster" | tee -a ${DOCKER_DISCORD_PY_FAILTMP:-/dev/null}; fi
if docker build --no-cache --build-arg DOCKER_REPO=${DOCKER_UPLOAD_REPOSITORY:-gorialis} --build-arg PYTHON_VERSION=3.7.4 --build-arg DISTRO=slim-buster --tag discord.py:build2-3.7.4-slim-buster --tag ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:build2-3.7.4-slim-buster .; then echo -e "BUILD build2-3.7.4-slim-buster" >> ${DOCKER_DISCORD_PY_PASSTMP:-/dev/null}; else echo -e "FAIL BUILD build2-3.7.4-slim-buster" | tee -a ${DOCKER_DISCORD_PY_FAILTMP:-/dev/null}; fi
if docker build --no-cache --build-arg DOCKER_REPO=${DOCKER_UPLOAD_REPOSITORY:-gorialis} --build-arg PYTHON_VERSION=3.7.4 --build-arg DISTRO=alpine --tag discord.py:build2-3.7.4-alpine --tag ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:build2-3.7.4-alpine .; then echo -e "BUILD build2-3.7.4-alpine" >> ${DOCKER_DISCORD_PY_PASSTMP:-/dev/null}; else echo -e "FAIL BUILD build2-3.7.4-alpine" | tee -a ${DOCKER_DISCORD_PY_FAILTMP:-/dev/null}; fi
if docker build --no-cache --build-arg DOCKER_REPO=${DOCKER_UPLOAD_REPOSITORY:-gorialis} --build-arg PYTHON_VERSION=3.6.9 --build-arg DISTRO=buster --tag discord.py:build2-3.6.9-buster --tag ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:build2-3.6.9-buster .; then echo -e "BUILD build2-3.6.9-buster" >> ${DOCKER_DISCORD_PY_PASSTMP:-/dev/null}; else echo -e "FAIL BUILD build2-3.6.9-buster" | tee -a ${DOCKER_DISCORD_PY_FAILTMP:-/dev/null}; fi
if docker build --no-cache --build-arg DOCKER_REPO=${DOCKER_UPLOAD_REPOSITORY:-gorialis} --build-arg PYTHON_VERSION=3.6.9 --build-arg DISTRO=slim-buster --tag discord.py:build2-3.6.9-slim-buster --tag ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:build2-3.6.9-slim-buster .; then echo -e "BUILD build2-3.6.9-slim-buster" >> ${DOCKER_DISCORD_PY_PASSTMP:-/dev/null}; else echo -e "FAIL BUILD build2-3.6.9-slim-buster" | tee -a ${DOCKER_DISCORD_PY_FAILTMP:-/dev/null}; fi
if docker build --no-cache --build-arg DOCKER_REPO=${DOCKER_UPLOAD_REPOSITORY:-gorialis} --build-arg PYTHON_VERSION=3.6.9 --build-arg DISTRO=alpine --tag discord.py:build2-3.6.9-alpine --tag ${DOCKER_UPLOAD_REPOSITORY:-gorialis}/discord.py:build2-3.6.9-alpine .; then echo -e "BUILD build2-3.6.9-alpine" >> ${DOCKER_DISCORD_PY_PASSTMP:-/dev/null}; else echo -e "FAIL BUILD build2-3.6.9-alpine" | tee -a ${DOCKER_DISCORD_PY_FAILTMP:-/dev/null}; fi
